spring.application.name=notification-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=ratchet
spring.datasource.password=ratchet
spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.auto-offset-reset=earliest
